### ISSUE TITLE
SwooleServerRequest构造ServerRequest出错

### ISSUE THREAD

**Issue by yyz26371945** [JanHuang/http#15]
更新了最新版http组件后，发现swoole模式下报错，发现是ServerRequest的构造函数第3个参数接收一个array类型，但是现在传递的request为一个object，因此报错
![image](https://user-images.githubusercontent.com/20291334/27117362-dcbd48ee-5108-11e7-8c72-fbdb411834af.png)
 之前这个没问题是因为header就是一个array，但是现在改了之后变成了一个object

**Comment by JanHuang** [comment]
OK，明白，确实是这个问题

**Comment by JanHuang** [comment]
@yyz26371945 已修复
