### ISSUE TITLE
请求头键名不规范

### ISSUE THREAD

**Issue by drsanwujiang** [JanHuang/http#32]
https://github.com/fastdlabs/http/blob/10825d892346fd5e635039d8929e2ce5befaaa88/src/SwooleServerRequest.php#L67

将请求头中的 - 替换成 _ 有点多余，且不符合标准。

**Comment by JanHuang** [comment]
有一点，主要是符合代码习惯，数组下划线

**Comment by drsanwujiang** [comment]
> 有一点，主要是符合代码习惯，数组下划线

是，不过一般getHeader的时候都是和标准名称一样用中划线的吧

**Comment by JanHuang** [comment]
> > 有一点，主要是符合代码习惯，数组下划线
> 
> 是，不过一般getHeader的时候都是和标准名称一样用中划线的吧

嗯，部分，不过这个建议接纳，这样子更加符合标准的方式。感谢建议
